export const WEATHER_CURRENT_SUCCESS = "WEATHER_CURRENT_SUCCESS"
export const WEATHER_CURRENT_LOADING = "WEATHER_CURRENT_LOADING"
export const WEATHER_CURRENT_ERROR = "WEATHER_CURRENT_ERROR"

export const WEATHER_DAILY_SUCCESS = "WEATHER_DAILY_SUCCESS"
export const WEATHER_DAILY_LOADING = "WEATHER_DAILY_LOADING"
export const WEATHER_DAILY_ERROR = "WEATHER_DAILY_ERROR"

export const WEATHER_HOURLY_SUCCESS = "WEATHER_HOURLY_SUCCESS"
export const WEATHER_HOURLY_LOADING = "WEATHER_HOURLY_LOADING"
export const WEATHER_HOURLY_ERROR = "WEATHER_HOURLY_ERROR"

